apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: employeemanager
  name: employeemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: employeemanager
    spec:
      containers:
      - image: docker.io/library/employeemanager:0.0.1-SNAPSHOT
        name: employeemanager
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employeemanager
  name: employeemanager
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: employeemanager
  type: LoadBalancer
status:
  loadBalancer: {}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: employeemanager
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: \"false\"
spec:
  rules:
  - http:
      paths:
      - path: /employeemanager
        backend:
          serviceName: employeemanager
          servicePort: 8080
