apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  
  labels:
    app: employeemanager
    name: employeemanager-Deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanager
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: employeemanager 
    spec:
      containers:
      - name: employeemanager
        image: farahhachicha/jenkins:latest
        ports:
        - containerPort: 3000
               
---
apiVersion: v1
kind: Service
metadata:
   creationTimestamp: null
spec:
  selector:
    app: employeemanager 
    name: employeemanager-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 3000
    nodePort: 31110

