
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: employeemanager
  name: employeemanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employeemanager
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: employeemanager
    spec:
      containers:
      - image: farahhachicha/jenkins:latest
        name: employeemanager
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: employeemanager
  name: employeemanager
spec:
  ports:
  - name: 8081-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: employeemanager
  type: ClusterIP
status:
  loadBalancer: {}
